# Site settings
title: Abel Nieva
subtitle: Front End Software Developer
email: abel@abelnieva.com
description: > # this means to ignore newlines until "baseurl:"
  Desarrollador de software, fotógrafo urbano, adicto al conocimiento, emprendedor, ensayista, enfocado en el estudio y exposición de la Biblia.
baseurl: "/personal-website" # the subpath of your site, e.g. /blog
url: "https://abelnieva.com" # the base hostname & protocol for your site
enforce_ssl: abelnieva.com
twitter_username: abelnieva
essays_categories: [memorias]

# Build settings
markdown: kramdown
incremental: false
paginate: 10
excerpt_separator: <!--more-->
exclude:
  [
    bower_components,
    node_modules,
    bower.json,
    gulpfile.js,
    LICENSE.txt,
    package.json,
    README.md,
  ]

# Gems
gems: [jekyll-paginate]

# Defaults

defaults:
  - scope:
      type: posts
    values:
      layout: post
      permalink: /ensayos/:title/
